#
# Sample Trafikverket weather information configuration file.

[DEFAULT]
# Id of weather station to pull data from. This one is for Lund.
#StationID = 1209
# And this one is for Dalby.
StationID = 1208

[MQTT]
MQTTBroker = nano.local
# Post combined observation on this topic
MQTTObservationTopic = home/observation
# Post outside temperature to this topic (eg '25.5' for a nice summer's day).
MQTTOutsideTemperatureTopic = home/temperature/outside
# Wind speed in mps.
MQTTWindSpeedTopic = home/wind/speed
# Wind gust in mps.
MQTTWindGustTopic = home/wind/gust
# Wind direction in degrees, that is "the direction the wind is blowing _from_"
# Eg. 180 indicates wind from south
MQTTWindDirectionTopic = home/wind/direction
# Precipitation type: 'noprecipitation', 'snow', 'rain'.
MQTTPrecipitationTypeTopic = home/precipitation/type
# Amount of precipitation (mm/h) if type != noprecipitation.
MQTTPrecipitationAmountTopic = home/precipitation/amount
# Retain published message
Retain = False
